version: '3.9'
services:
  api:
    build:
        context: .
        dockerfile: docker/node/Dockerfile
    container_name: api
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/app
    environment:
      - PORT=${PORT:-3000}